### ISSUE TITLE
Docker Image: No module named Torch

### ISSUE THREAD

**Issue by Spandan-Madan** [PkuRainBow/OCNet#17]
Hi @PkuRainBow, I tried running the docker version of the code. Here's my  command and error:-

```
smadan@thousandeyes:/data/graphics/toyota-pytorch/OCNet$ sudo docker run rainbowsecret/pytorch04:20180905 python inplace_abn/test_imagenet.py
Traceback (most recent call last):
  File "inplace_abn/test_imagenet.py", line 5, in <module>
    import torch
ImportError: No module named torch

```

**Comment by PkuRainBow** [comment]
I guess you fail to specify the correct path to the python.

**Comment by Spandan-Madan** [comment]
Not very familiar with docker actually.

I ran the command :- 

```
sudo docker run rainbowsecret/pytorch04:20180905 python inplace_abn/test_imagenet.py
Traceback (most recent call last):
```

That should default to the python that comes with the docker, right? Or my python?

**Comment by PkuRainBow** [comment]
You should specify the path of pytorch "/root/miniconda3/bin/python"
