### ISSUE TITLE
CVPR

### ISSUE THREAD

**Issue by winwinJJiang** [PkuRainBow/OCNet#21]

**Comment by PkuRainBow** [comment]
@winwinJJiang Sorry, there seems no discription.

**Comment by winwinJJiang** [comment]
Hi, I mean I found some mistakes in your paper and just one to point it out
if you do not mind.


RainbowSecret <notifications@github.com> 于2018年10月2日周二 上午10:27写道：

**Comment by PkuRainBow** [comment]
@winwinJJiang Ok, please share me the mistakes that you find. I will fix them in the latter version.

Thanks for your attention on our work.

**Comment by winwinJJiang** [comment]
It's mainly about the introduction. Self-attention is not proposed by the
"attention is all you need.", just
a fundamental issue.



RainbowSecret <notifications@github.com> 于2018年10月2日周二 下午3:39写道：

**Comment by PkuRainBow** [comment]
@winwinJJiang In fact, I find that the word "self-attention" is firsly used by the nips2017 paper.

Please show me the earlier work if you know exactly. Besides, I find there used to be some similar work use a term "intra-attention".

**Comment by winwinJJiang** [comment]
Yes. Self-attention/intra-attention is the same thing.
https://arxiv.org/pdf/1703.03130.pdf   Here is the paper that proposed
before the GG paper.

Please check and let me know whether I am right or wrong.

Thank you!

RainbowSecret <notifications@github.com> 于2018年10月2日周二 下午5:57写道：

**Comment by PkuRainBow** [comment]
@winwinJJiang Thanks for your advice. I will check the issue and fix it latter.

**Comment by winwinJJiang** [comment]
Good luck with your submission!

RainbowSecret <notifications@github.com> 于2018年10月2日周二 下午7:33写道：
