### ISSUE TITLE
inplace_bn build failed

### ISSUE THREAD

**Issue by KeyKy** [PkuRainBow/OCNet#22]
/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py:118: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Traceback (most recent call last):
  File "/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 759, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/data00/kangyang/python3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/data00/kangyang/python3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 27, in <module>
    from network import get_segmentation_model
  File "/data00/kangyang/segmentation/OCNet/network/__init__.py", line 1, in <module>
    from .resnet101_baseline import get_resnet101_baseline
  File "/data00/kangyang/segmentation/OCNet/network/resnet101_baseline.py", line 27, in <module>
    from resnet_block import conv3x3, Bottleneck
  File "/data00/kangyang/segmentation/OCNet/network/../utils/resnet_block.py", line 19, in <module>
    from bn import InPlaceABNSync
  File "/data00/kangyang/segmentation/OCNet/utils/../inplace_abn/bn.py", line 14, in <module>
    from functions import *
  File "/data00/kangyang/segmentation/OCNet/utils/../inplace_abn/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 682, in _jit_compile
    _build_extension_module(name, build_directory)
  File "/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 765, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'inplace_abn': [1/4] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/TH -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/data00/kangyang/virtualenv3.6/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data00/kangyang/segmentation/OCNet/inplace_abn/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/TH -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/data00/kangyang/virtualenv3.6/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data00/kangyang/segmentation/OCNet/inplace_abn/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/ATen/Half-inl.h(17): error: identifier "__half_as_short" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00011718_00000000-7_inplace_abn_cuda.cpp1.ii".
[2/4] c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/TH -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/data00/kangyang/virtualenv3.6/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /data00/kangyang/segmentation/OCNet/inplace_abn/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
/data00/kangyang/segmentation/OCNet/inplace_abn/src/inplace_abn_cpu.cpp: In function ‘std::vector<at::Tensor> backward_cpu(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, bool, float)’:
/data00/kangyang/segmentation/OCNet/inplace_abn/src/inplace_abn_cpu.cpp:82:41: warning: ‘at::Tensor at::empty(const at::Type&, at::IntList)’ is deprecated (declared at /data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/ATen/Functions.h:3521) [-Wdeprecated-declarations]
   auto dweight = at::empty(z.type(), {0});
                                         ^
/data00/kangyang/segmentation/OCNet/inplace_abn/src/inplace_abn_cpu.cpp:83:39: warning: ‘at::Tensor at::empty(const at::Type&, at::IntList)’ is deprecated (declared at /data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/ATen/Functions.h:3521) [-Wdeprecated-declarations]
   auto dbias = at::empty(z.type(), {0});
                                       ^
[3/4] c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/TH -I/data00/kangyang/virtualenv3.6/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/data00/kangyang/virtualenv3.6/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /data00/kangyang/segmentation/OCNet/inplace_abn/src/inplace_abn.cpp -o inplace_abn.o
ninja: build stopped: subcommand failed.

Could you help me with this error? What's your CUDA Version and gcc version. I use cuda8.0 and gcc 4.9.2

**Comment by PkuRainBow** [comment]
Please use pytorch0.4.1.

There is no need to build the inplace-abn. Besides, please open the issue related to inplace-abn in the source repo(https://github.com/mapillary/inplace_abn) instead of here.

**Comment by KeyKy** [comment]
@PkuRainBow  My pytorch is 0.4.1. I run this script ./run_resnet101_asp_oc.sh and I get this error.

**Comment by KeyKy** [comment]
I don't find the this script run_asp_oc.sh

**Comment by KeyKy** [comment]
@

**Comment by PkuRainBow** [comment]
@KeyKy I have tested 2 images with a single GPU and succeeded.

**Comment by KeyKy** [comment]
@PkuRainBow 谢谢 我有4块1080 Ti的GPU，只能每张卡跑batch_size=1的，总共batch_size=4。最后我在验证集上的指标是：

```
{'meanIU': 0.7837545863719357, 'IU_array': array([0.98047586, 0.84426419, 0.92612712, 0.63912455, 0.62647073,0.6292012 , 0.69047148, 0.78069628, 0.9247761 , 0.65401277,0.94481553, 0.81283084, 0.63479937, 0.94911405, 0.81046328,0.86166291, 0.75384313, 0.66243928, 0.76574848])}
```
所以说我应该要4张P100 16G的显存才能完全复现你的效果吗？还有其他办法吗，因为我没那么好的机器

**Comment by PkuRainBow** [comment]
@KeyKy Batch size很重要，batch size=8可以保证复现结果的。

**Comment by KeyKy** [comment]
@PkuRainBow 我发现https://github.com/zhuangyqin/DRN 这个貌似在leaderboard上有82.8的IOU classes。

**Comment by PkuRainBow** [comment]
@KeyKy Please use English for the discussion.

Besides, the huge memory cost is one of the main drawback of the self-attention method.

We are trying to propose better method to reduce the memory cost largely while maintaining the performance.

**Comment by KeyKy** [comment]
@PkuRainBow self-attention also increase the whole amount of computation. Maybe I can reduce these computation of self-attention and put these by increasing Convolution operations into backbone network. I also can get the same performance.

**Comment by PkuRainBow** [comment]
@KeyKy I do not agree with you.

**Comment by KeyKy** [comment]
@PkuRainBow 我找了4块V100，跑了一个batch-size=8的实验，./run_resnet101_asp_oc.sh 最终test集上的结果是：

IoU Classes | 77.232
iIoU Classes | 54.5597
IoU Categories | 90.129
iIoU Categories | 77.602

是不是要用OHEM继续提点？我就只训练gtFineTrain，没有吧gtFineVal加入训练。

看了你的论文指标，
Method train mIoU(%) val mIoU(%)
ResNet101+ASP-OC 85.720 79.580

我试了下我的是：
ResNet101+ASP-OC 85.7 78.380

**Comment by PkuRainBow** [comment]
Hi, your results seems not as good as the number reported in the paper.

What is the version of the pytorch? Besides, you are expected to achieve ~79.5 on the validation set without OHEM.

**Comment by KeyKy** [comment]
@PkuRainBow The second run 

```
{'meanIU': 0.7872904663594398, 'IU_array': array([0.98359365, 0.86381204, 0.9273207 , 0.55040593, 0.63191286, 0.65154667, 0.7169406 , 0.80020197, 0.92748692, 0.67367246, 0.95001835, 0.82902815, 0.66007207, 0.95481035, 0.80353403,0.85126102, 0.73285753, 0.66668435, 0.78335922])}
```

**Comment by PkuRainBow** [comment]
@KeyKy Great! 

I believe you could achieve much better performance with the OHEM! I also recommend you to run the experiments for more than 2 times to ensure one performance is good.
