### ISSUE TITLE
What is ‘GC’ in Tables 6 and 7？

### ISSUE THREAD

**Issue by qiulesun** [PkuRainBow/OCNet#23]
**Question 1：**
As shown in Tables 6 and 7, can you detail the GC operation?
**Question 2：**
I think this paper should give the SA a more specific name, making it  straightforward and easy understand.
**Question 3：**
Is this paper submitted to the CVPR2019?

**Comment by PkuRainBow** [comment]
Thanks for your advice.  We will update the paper on the arXiv in future weeks.

Q-1
The GC is the same as the ParsingNet that employ the global average pooling based context.

Q-2
Do you have any advice about a better name of the SA? Maybe "Approximated Object Context".

Q-3
We are still polishing our work.
