### ISSUE TITLE
The issue about resnet-101 mean/val of input image

### ISSUE THREAD

**Issue by lyakaap** [PkuRainBow/OCNet#24]
Thanks for the great work, and your paper is quite interesting.

I noticed that preprocessing of resnet-101's input contradicts torchvision pretrained models 
* https://pytorch.org/docs/stable/torchvision/models.html
* https://github.com/PkuRainBow/OCNet/blob/5b6871a11dc10d856219aea275f1a48edc7cd260/dataset/cityscapes.py#L98-L101

I think that you use torchvision pretrained resnet101 to achieve the performances described at your paper. So please correct me if I'm wrong.

**Comment by PkuRainBow** [comment]
@lyakaap We use the pretrained resnet101 provided by https://github.com/CSAILVision/semantic-segmentation-pytorch.

Here is the link to the model http://sceneparsing.csail.mit.edu/model/pretrained_resnet/.

**Comment by lyakaap** [comment]
Thank you very much!
