### ISSUE TITLE
inference bug

### ISSUE THREAD

**Issue by SwagJzzZ** [PkuRainBow/OCNet#26]
Hi PkuRainBow,
 There is a bug in ```generate_submit.py```, where only ```scale >1 ``` will resize the input image and, as a result, the 0.75 scale will not be activated.

```def predict_whole_img(net, image, classes, method, scale):
    """
         Predict the whole image w/o using multiple crops.
         The scale specify whether rescale the input image before predicting the results.
    """
    N_, C_, H_, W_ = image.shape

    if torch_ver == '0.4':
        interp = nn.Upsample(size=(H_, W_), mode='bilinear', align_corners=True)
    else:
        interp = nn.Upsample(size=(H_, W_), mode='bilinear')

    if scale > 1:
        scaled_img = ndimage.zoom(image, (1.0, 1.0, scale, scale), order=1, prefilter=False)
    else:
        scaled_img = image```

**Comment by PkuRainBow** [comment]
So..... Do you mean I only employ two scales for test set?......

**Comment by SwagJzzZ** [comment]
Yes, I have debug it. The shape of the output features before upsampling, are the same for scale 0.75 and 1.0. 
By the way, have you test on more scales, such as 0.5 0.75 1.25 1.5 1.75 2.0 .

**Comment by PkuRainBow** [comment]
I think more scales can improve the performance..... I just try some scales to save the time. 

It takes much more time if you test with too many scales.

**Comment by SwagJzzZ** [comment]
Yes, I found that the test method is do time consuming, especially, the ```sliding``` testing. Therefore, for scale > 1, I adopt full input for testing, then resize the output to 1024,2048. It may consume more GPU memory, but significantly reduce the testing time and performance keeps similar.

**Comment by PkuRainBow** [comment]
@SwagJzzZ I do not employ the sliding method, which is too slow.

**Comment by SwagJzzZ** [comment]
@PkuRainBow you mean that all the scale, you adopt the function ```predict_whole_img``` ?

**Comment by PkuRainBow** [comment]
Yes. But it seems the memory is not enough for larger scale such as 1.75x and 2x.

**Comment by PkuRainBow** [comment]
@SwagJzzZ Currently, we could achieve 81.54 on the testing set of CS by fixing the multi-scale bugs.

And we will keep improving this number in the recent week.

**Comment by PkuRainBow** [comment]
@SwagJzzZ The original scales [0.75x, 1x, 1.25x] is OK.

**Comment by SwagJzzZ** [comment]
@PkuRainBow Thanks for your reply. I am trying to train the model on VOC2012.

**Comment by PkuRainBow** [comment]
@SwagJzzZ Great!

We plan to add the experiments on VOC2012 in the futher month.

It would be great if you could share your results with us in advance.
