### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by DW1HH** [PkuRainBow/OCNet#28]
!! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Traceback (most recent call last):
  File "/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 759, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/home/huhuai/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/huhuai/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 28, in <module>
    from network import get_segmentation_model
  File "/home/huhuai/Project/OCNet/network/__init__.py", line 1, in <module>
    from .resnet101_baseline import get_resnet101_baseline
  File "/home/huhuai/Project/OCNet/network/resnet101_baseline.py", line 27, in <module>
    from resnet_block import conv3x3, Bottleneck
  File "/home/huhuai/Project/OCNet/network/../utils/resnet_block.py", line 19, in <module>
    from bn import InPlaceABNSync
  File "/home/huhuai/Project/OCNet/utils/../inplace_abn/bn.py", line 14, in <module>
    from functions import *
  File "/home/huhuai/Project/OCNet/utils/../inplace_abn/functions.py", line 16, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 514, in load
    with_cuda=with_cuda)
  File "/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 682, in _jit_compile
    _build_extension_module(name, build_directory)
  File "/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 765, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'inplace_abn': [1/2] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/include -I/home/huhuai/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/huhuai/Project/OCNet/inplace_abn/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o 
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -I/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/include -I/home/huhuai/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/huhuai/Project/OCNet/inplace_abn/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/home/huhuai/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Half-inl.h(17): error: identifier "__half_as_short" is undefined

3 errors detected in the compilation of "/tmp/tmpxft_000055e7_00000000-7_inplace_abn_cuda.cpp1.ii".
ninja: build stopped: subcommand failed.

when i run python evel.py,the above error occurred.

**Comment by DW1HH** [comment]
thank you

**Comment by SwagJzzZ** [comment]
@DW1HH if it does not work, try this one https://www.claudiokuenzler.com/blog/756/install-newer-ninja-build-tools-ubuntu-14.04-trusty#.W-ko83UzZhF

**Comment by DW1HH** [comment]
@SwagJzzZ @PkuRainBow  I replaced inplace_abn with nn.BatchNorm2d solved my problem,but i only got 60% miou. my input_size=500,500   batch_size=8, trained on 4 1080ti gpu.　does the input_size or nn.nn.BatchNorm2d　influenced the precision?

**Comment by PkuRainBow** [comment]
2333333 Of course. I think if you should access **8 x 1080** or **4 X P100** if you want to reproduce all of our experiments.
