### ISSUE TITLE
why not try VOC dataset

### ISSUE THREAD

**Issue by idealwei** [PkuRainBow/OCNet#29]
I've read your paper and I know your task is scene parsing. But why not experimenting on Pascal VOC datasets ?  Will OCNet achive SoTA on VOC too ?

**Comment by PkuRainBow** [comment]
We don't have a good baseline on VOC dataset.

**Comment by idealwei** [comment]
Can you try to explain why ? Did you train VOC like deeplabv3plus does ? It's very hard to finetune the model to get such  high scores on VOC dataset.  And i want to know if OCNet performs better than PSPNet or Deeplabv3 on VOC datasets. I remember the author of Deeplabv3plus remove average global pooling of ASPP and get better results on cityscapes datasets  and prove image pooing is more suitable to VOC dataset. I think if you can also get a better score on pascal voc dataset you can get an oral.

**Comment by PkuRainBow** [comment]
@idealwei Thanks for your advice.

In fact, we also want to validate our method on VOC. But our baseline is far from the current state-of-the-art method. 

It requires much more tricks to achieve good performance on VOC.

It would be great if you have access to Pytorch based baseline on VOC dataset. We can conduct the related experiments quickly.

We believe that Object Context is a very general concept towards better segmentation performance.

**Comment by idealwei** [comment]
@PkuRainBow. You can refer to [GluonCV](https://gluon-cv.mxnet.io/model_zoo/segmentation.html#semantic-segmentation) and [here](https://github.com/zhanghang1989/gluoncv-torch) is its PyTorch implementation. Hope that can help.
