### ISSUE TITLE
Good paper need good codes.

### ISSUE THREAD

**Issue by lihua213** [PkuRainBow/OCNet#3]
Thanks for your good paper. now the star is almost 100 and you release your code?

**Comment by PkuRainBow** [comment]
@lihua213 Thanks for your notice. We promise that we will release our code once the star count exceeds 100.

**Comment by liaopeiyuan** [comment]
:) 
<img width="106" alt="screen shot 2018-09-12 at 7 44 45 pm" src="https://user-images.githubusercontent.com/34192321/45458987-545c9900-b6c4-11e8-8dbb-c3bb121e4839.png">

**Comment by PkuRainBow** [comment]
@lihua213 @liaopeiyuan Please try our code! Good luck!
