### ISSUE TITLE
Issues about your paper writing.

### ISSUE THREAD

**Issue by idealwei** [PkuRainBow/OCNet#33]
Hi, Its me again. I think you have submmited your paper already. 

First of all, i want to say that i admire your work very much. But after reading your arXiv preprint version again, I found a serious problem that you haven't mentioned [DANet](https://arxiv.org/pdf/1809.02983.pdf) or compare to it at all. **DANet** is accepted by ECCV2018 and i think both **OCNet** and **DANet** have very similar ideas and very close score on Cityscapes but with different interpretation.  In my opinion, it's necessary to clarify the differece between them. However, you didn't for some reason. Can your try to explain ? 

At last, hope your paper could be accepted.

**Comment by PkuRainBow** [comment]
Thanks for your kind remind.

.......DANet is after our work.... You could check the dates on the arxiv.

Besides, DANet is submitted to the AAAI-2019.
