### ISSUE TITLE
"strange question": size of W ?

### ISSUE THREAD

**Issue by AceCoooool** [PkuRainBow/OCNet#4]
Already Know：W --- whxwh,  input size --- 769x769,  ---> wh=(769/8)x(769/8)=9216
Parameter of W: 9216x9216=84934656
Parameter of ResNet101：44549160

The parameter of W is larger than bone net (ResNet101)，stange and crazy? 
Is it my misunderstand ?

thank you ~

**Comment by PkuRainBow** [comment]
@AceCoooool That is not the parameter. We only need 1x1 convolution. Besides, we can down-sample the output feature map within the Base-OC block. Please wait for the open source implementation.

**Comment by AceCoooool** [comment]
thank you :smile: ~ there is "unrelated" between each row of W, may many methods can deal with it (I guess). Looking forward to the implementation, thank you :heart:
