### ISSUE TITLE
关于ASP-OC

### ISSUE THREAD

**Issue by kikyou123** [PkuRainBow/OCNet#7]
十分感谢作者开放源码，我对于论文有个小的困惑。
作者声明在ASP-OC中只用到第一个分支可以取得最好的结果。但是如果ASP-OC只采用第一分支的话，我认为和Base-OC是相同的，并不存在multi-scale。不知道为什么ASP-OC的性能会大量优于Base-OC。

**Comment by PkuRainBow** [comment]
@kikyou123 没有大量优于，你可以试验一下，base-oc可以达到comparable的性能。

**Comment by kikyou123** [comment]
![image](https://user-images.githubusercontent.com/19486038/45665004-6d8c9c00-bb41-11e8-92ae-ee31cbe8da87.png)
从论文上看是有提高的，但是看上去这两个模型是一样的，请问base-oc和单分支的asp-oc有什么区别吗

**Comment by PkuRainBow** [comment]
@kikyou123 请看代码。
